[package]
name = "learning-impl"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "naive-trie"
path = "src/trie/naive.rs"


[[bin]]
name = "radix-trie"
path = "src/trie/radix.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]



